# netlify.toml
[build]
  publish = "public"  # 또는 실제 정적 파일이 있는 디렉토리
  command = ""        # 빌드 커맨드가 필요없다면 비워두세요

# 기본 리디렉션 (모든 경로에 대한 폴백)
[[redirects]]
  from = "/*"
  to = "https://justbu.me/sagyo/:splat"
  status = 301
  force = true

# 특정 경로에 대한 리디렉션
[[redirects]]
  from = "/profile/*"
  to = "https://justbu.me/profile/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/chat/*"
  to = "https://justbu.me/chat/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/login"
  to = "https://justbu.me/login"
  status = 301
  force = true

[[redirects]]
  from = "/chat_list"
  to = "https://justbu.me/chat_list"
  status = 301
  force = true

[[redirects]]
  from = "/notification"
  to = "https://justbu.me/notification"
  status = 301
  force = true

[[redirects]]
  from = "/setting"
  to = "https://justbu.me/setting"
  status = 301
  force = true
